# Generated by Django 4.1.4 on 2022-12-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
